name: Gardener - Fix Technical Debt Issues

on:
  issues:
    types: [opened, labeled]

jobs:
  fix-technical-debt:
    runs-on: ubuntu-latest
    # Only process issues created by 2mawi2 with technical-debt label
    if: |
      contains(github.event.issue.labels.*.name, 'technical-debt') &&
      github.event.issue.user.login == '2mawi2'
    permissions:
      contents: write
      pull-requests: write
      issues: write
      id-token: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install just
        uses: extractions/setup-just@v2

      - name: Create working branch
        run: |
          # Create branch name from issue number and title
          BRANCH_NAME="fix/issue-${{ github.event.issue.number }}-$(echo "${{ github.event.issue.title }}" | tr '[:upper:]' '[:lower:]' | tr ' ' '-' | tr -cd '[:alnum:]-' | cut -c1-50)"
          git checkout -b "$BRANCH_NAME"
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT
        id: branch

      - name: Fix technical debt issue
        uses: 2mawi2/claude-code-action-extended@main
        with:
          use_oauth: true
          model: "claude-sonnet-4-20250514"
          claude_access_token: ${{ secrets.CLAUDE_ACCESS_TOKEN }}
          claude_refresh_token: ${{ secrets.CLAUDE_REFRESH_TOKEN }}
          claude_expires_at: ${{ secrets.CLAUDE_EXPIRES_AT }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          direct_prompt: |
            You are working on fixing the following technical debt issue:
            
            Issue #${{ github.event.issue.number }}: ${{ github.event.issue.title }}
            
            ${{ github.event.issue.body }}
            
            Please:
            1. Understand the issue thoroughly
            2. Implement the fix following best practices
            3. Ensure all tests pass after your changes
            4. Run linting to ensure code quality
            5. Commit your changes with a descriptive message
            6. Comment on the issue with a summary of what you did
            
            Important:
            - Make focused changes that address only this specific issue
            - Write clean, well-documented code
            - Add tests if necessary
            - Use `git add -A && git commit -m "fix: [description] (closes #${{ github.event.issue.number }})"` for the commit
          allowed_tools: "Bash(*),Edit(*),Read(*),Write(*),MultiEdit(*),Glob(*),Grep(*),LS(*),TodoRead,TodoWrite,mcp__github__create_comment"
          timeout_minutes: "45"

      - name: Push changes
        run: |
          git push -u origin "${{ steps.branch.outputs.branch_name }}"

      - name: Create pull request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          branch: ${{ steps.branch.outputs.branch_name }}
          title: "🌿 Fix: ${{ github.event.issue.title }}"
          body: |
            ## 🌿 Gardener Automated Fix
            
            This PR fixes the technical debt identified in #${{ github.event.issue.number }}
            
            ### 📋 Issue Description
            ${{ github.event.issue.title }}
            
            ### 🔧 Changes Made
            The Gardener has automatically implemented a fix for this technical debt issue.
            
            ### ✅ Checklist
            - [ ] All tests pass
            - [ ] Code follows project conventions
            - [ ] No breaking changes introduced
            
            Closes #${{ github.event.issue.number }}
            
            ---
            *This PR was created automatically by the Gardener workflow*