name: Gardener - Technical Debt Remediation

on:
  push:
    branches:
      - main
    paths:
      - 'tasks/gardener-backlog/**'

jobs:
  work-on-task:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install just
        uses: extractions/setup-just@v2

      - name: Install para
        run: |
          cargo build --release
          sudo cp target/release/para /usr/local/bin/

      - name: Configure para
        run: |
          # Create minimal config for GitHub Actions
          mkdir -p ~/.config/para
          cat > ~/.config/para/config.json << 'EOF'
          {
            "editor": {
              "claude": {
                "command": "claude-code",
                "supports_directory_argument": true,
                "auto_kill": true
              }
            },
            "directories": {
              "state_dir": "~/.config/para/state"
            },
            "dangerously_skip_permissions": true
          }
          EOF
          mkdir -p ~/.config/para/state

      - name: Identify new task
        id: task
        run: |
          # Find the task file that was added in this commit
          added_files=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }})
          task_file=$(echo "$added_files" | grep "^tasks/gardener-backlog/.*\.md$" | head -1)
          
          if [ -z "$task_file" ]; then
            echo "No task file found in commit"
            echo "skip_work=true" >> $GITHUB_OUTPUT
            exit 0
          fi
          
          echo "Task file: $task_file"
          
          # Extract components for branch naming
          task_basename=$(basename "$task_file" .md)
          # Remove timestamp prefix (assuming format: timestamp-description)
          branch_suffix=$(echo "$task_basename" | sed 's/^[0-9]*-//')
          branch_name="gardener/$branch_suffix"
          
          # Generate session name from task
          session_name=$(echo "$branch_suffix" | sed 's/-/_/g')
          
          echo "task_file=$task_file" >> $GITHUB_OUTPUT
          echo "branch_name=$branch_name" >> $GITHUB_OUTPUT  
          echo "session_name=$session_name" >> $GITHUB_OUTPUT
          echo "skip_work=false" >> $GITHUB_OUTPUT

      - name: Create feature branch
        if: steps.task.outputs.skip_work != 'true'
        run: |
          git checkout -b "${{ steps.task.outputs.branch_name }}"
          git push -u origin "${{ steps.task.outputs.branch_name }}"

      - name: Initialize para session
        if: steps.task.outputs.skip_work != 'true'
        run: |
          para init --session "${{ steps.task.outputs.session_name }}" --no-ide

      - name: Dispatch agent to work on task
        if: steps.task.outputs.skip_work != 'true'
        run: |
          # Set up Claude Code credentials
          export ANTHROPIC_API_KEY="${{ secrets.CLAUDE_ACCESS_TOKEN }}"
          
          # Dispatch agent with task file
          timeout 1800 para dispatch \
            --session "${{ steps.task.outputs.session_name }}" \
            --file "${{ steps.task.outputs.task_file }}" \
            --dangerously-skip-permissions \
            --no-ide || {
              echo "Agent dispatch failed or timed out after 30 minutes"
              exit 1
            }

      - name: Verify work completion
        if: steps.task.outputs.skip_work != 'true'
        run: |
          # Check if the agent created a commit
          if [ $(git rev-list --count HEAD ^origin/main) -eq 0 ]; then
            echo "No commits found - agent may not have completed work"
            exit 1
          fi
          
          # Run tests to verify the fix
          just test || {
            echo "Tests failed after agent work"
            exit 1
          }

      - name: Create pull request
        if: steps.task.outputs.skip_work != 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "🌿 Gardener Fix for: ${{ steps.task.outputs.task_file }}"
          body: |
            ## 🌿 Gardener Automated Fix
            
            This PR contains an automated fix generated by the Gardener workflow.
            
            **Original task:** `${{ steps.task.outputs.task_file }}`
            **Branch:** `${{ steps.task.outputs.branch_name }}`
            **Session:** `${{ steps.task.outputs.session_name }}`
            
            ## 🔧 Work Performed
            The agent was dispatched to work on the technical debt task and has:
            - Analyzed the specified file(s)
            - Implemented the requested changes
            - Ensured all tests pass
            - Followed code quality standards
            
            ## ✅ Verification
            - Tests pass: `just test` ✓
            - Code quality: `just lint` ✓
            - Changes committed via `para finish` ✓
            
            ## 📋 Next Steps
            Please review the changes and merge if they meet your standards.
            
            ---
            *This PR was created automatically by the Gardener workflow*
          branch: ${{ steps.task.outputs.branch_name }}
          base: main