name: Technical Debt Handler

on:
  issues:
    types: [opened]

jobs:
  trigger-claude:
    runs-on: ubuntu-latest
    # Only trigger when:
    # 1. Issue is created by github-actions app (the Auditor)
    # 2. Issue has the technical-debt label
    # This ensures we only auto-trigger for Auditor-created issues
    if: |
      github.event.action == 'opened' &&
      github.event.issue.user.login == 'app/github-actions' &&
      contains(github.event.issue.labels.*.name, 'technical-debt')
    permissions:
      issues: write
    
    steps:
      - name: Wait for GitHub to process the issue
        run: |
          echo "Waiting 15 seconds to ensure issue is fully processed..."
          sleep 15
        
      - name: Check for existing @claude comments
        id: check_comments
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          echo "Checking for existing @claude comments on issue #${{ github.event.issue.number }}..."
          
          CLAUDE_COMMENTS=$(gh api /repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments \
            --jq '[.[] | select(.body | contains("@claude"))] | length')
          
          echo "Found $CLAUDE_COMMENTS existing @claude comments"
          echo "has_claude_comment=$([[ $CLAUDE_COMMENTS -gt 0 ]] && echo 'true' || echo 'false')" >> $GITHUB_OUTPUT
        
      - name: Add @claude comment if none exists
        if: steps.check_comments.outputs.has_claude_comment == 'false'
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          echo "No existing @claude comment found, adding one..."
          gh issue comment ${{ github.event.issue.number }} \
            --body "@claude please fix this technical debt issue" \
            --repo ${{ github.repository }}
          echo "Comment added successfully"