name: Test

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  test:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Configure Git and Environment
      run: |
        # Configure git properly for CI environment
        git config --global user.email "test@example.com"
        git config --global user.name "GitHub Actions"
        git config --global init.defaultBranch main
        git config --global core.autocrlf false
        git config --global core.filemode false
        git config --global advice.detachedHead false
        
        # Ensure we have proper permissions
        umask 022
        
        # Set environment variables for para
        echo "IDE_NAME=cursor" >> $GITHUB_ENV
        echo "IDE_CMD=echo" >> $GITHUB_ENV
        echo "CURSOR_CMD=echo" >> $GITHUB_ENV
        echo "PARA_NON_INTERACTIVE=true" >> $GITHUB_ENV
    
    - name: Install dependencies
      run: |
        brew install shellcheck bats-core shfmt
    
    - name: Run shellcheck
      run: |
        shellcheck -e SC1091,SC2086 para.sh install-para.sh lib/*.sh
    
    - name: Run shfmt check
      run: |
        shfmt -d -i 2 para.sh install-para.sh lib/*.sh
    
    - name: Debug test environment
      run: |
        echo "🔍 Debug info:"
        echo "Current directory: $(pwd)"
        echo "Current user: $(whoami)"
        echo "Umask: $(umask)"
        echo "Git version: $(git --version)"
        echo "IDE_NAME: ${IDE_NAME:-unset}"
        echo "IDE_CMD: ${IDE_CMD:-unset}"
        echo "PARA_NON_INTERACTIVE: ${PARA_NON_INTERACTIVE:-unset}"
        echo "Available disk space:"
        df -h .
        echo "Temporary directory permissions:"
        ls -la /tmp | head -5
    
    - name: Run tests with better error handling
      env:
        # Ensure tests have proper environment
        IDE_NAME: cursor
        IDE_CMD: echo
        CURSOR_CMD: echo
        PARA_NON_INTERACTIVE: true
      run: |
        echo "🧪 Running all para tests..."
        
        # Run each test suite separately with better error handling
        echo "Running unit tests..."
        if ! bats tests/test_para_units.bats; then
          echo "❌ Unit tests failed"
          exit 1
        fi
        
        echo "Running prompt feature tests..."
        if ! bats tests/test_para_prompt_features.bats; then
          echo "❌ Prompt feature tests failed"
          exit 1
        fi
        
        echo "Running argument parsing tests..."
        if ! bats tests/test_para_argument_parsing.bats; then
          echo "❌ Argument parsing tests failed"
          exit 1
        fi
        
        echo "Running friendly names tests..."
        if ! bats tests/test_friendly_names.bats; then
          echo "❌ Friendly names tests failed"
          echo "🔍 Attempting to debug the first failing test..."
          
          # Create a minimal debug test
          TEST_REPO=$(mktemp -d)
          echo "Debug test repo: $TEST_REPO"
          cd "$TEST_REPO"
          
          # Setup git repo
          git init
          git config user.email "test@example.com" 
          git config user.name "Test User"
          echo "test content" > test-file.py
          git add test-file.py
          git commit -m "Initial commit"
          
          # Try to run para with debug output
          echo "Attempting to run para start..."
          if ! PARA_NON_INTERACTIVE=true IDE_CMD="echo" IDE_NAME="cursor" "$(pwd)/../para.sh" start 2>&1; then
            echo "❌ Para start failed"
            echo "Directory contents:"
            ls -la
            echo "Git status:"
            git status
            echo "Git log:"
            git log --oneline
          else
            echo "✅ Para start succeeded in debug test"
          fi
          
          cd ..
          rm -rf "$TEST_REPO"
          exit 1
        fi
        
        echo "Running integration tests..."
        if ! bats tests/test_para_integration.bats; then
          echo "❌ Integration tests failed"
          exit 1
        fi
        
        echo "✅ All tests passed!"
    
    - name: Test installation
      run: |
        echo "🧪 Testing installation..."
        ./install-para.sh
        
        # Test that para is available
        export PATH="$HOME/.local/bin:$PATH"
        which para
        PARA_NON_INTERACTIVE=true para --help 